plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - "**/*.gemspec"

Metrics/ClassLength:
  Enabled: true
  Max: 250
  Exclude:
    - "lib/litellm/client.rb"

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
